name: flutter_day_1
description: "A new Flutter project."
# publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: asset/fonts/Roboto-Regular.ttf
        - asset: asset/fonts/Roboto-Bold.ttf
        - asset: asset/fonts/Roboto-Black.ttf
          weight: 700
